### ISSUE TITLE
Upload to PYPI

### ISSUE THREAD

**Issue by miguelmsemprun** [HIIT/Ledapy#2]
I have tested your code and it works great, so I am using it in my master thesis. Could you upload it in Pypi?

**Comment by MarcoFiletti** [comment]
Hi, sorry I missed your comment. Are you still interested in this?

**Comment by miguelmsemprun** [comment]
Yes please, I’m really interested

**Comment by MarcoFiletti** [comment]
Hello, the package is now available on pipy `pip3 install ledapy`. Note that matplotlib is not installed as a dependency since it is not really required for the package to work.

**Comment by miguelmsemprun** [comment]
Thank you very much
