### ISSUE TITLE
how to import both event and raw EDA signals

### ISSUE THREAD

**Issue by IGHOYOTA** [HIIT/Ledapy#4]
Hello,

Thank for making this great tool.

I use ledlab mathlab for eda analysis,  and i am able to upload the raw eda signals and event files to perform event related analysis (feature extraction).

However, i have been trying to see how that could be possible with the python verssion but still dont get.

can you be kind to point me in the right direction on how to import both event and raw signal data using this python tool.

Looking forward to your reply

Best Regards 

ben

**Comment by MarcoFiletti** [comment]
Hello, thanks for your question

there is no support for event-based analysis import from Ledalab, event-related processing would need to be done manually in python.

For example, one way to do it would be to calculate total phasic "activity" within a time window using a summation. For example, if you know event 1 happened between seconds 2 and 3 and your sampling rate is 1000 Hz, you could use

`numpy.sum(phasicData[2000:3000])`

This would give you a single number for event 1, which you can then compare against other events. You could use the same principle to calculate other features for that event (e.g. number of peaks, height of maximum peak, etc)
